kind: ConfigMap
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  labels:
    component: frontend-deployment
    project: expense
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      tier: web
      project: expense
      environment: dev
  template:
    metadata:
      name: frontend
      labels:
        component: frontend
        tier: web
        project: expense
        environment: dev
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        ports:
        - containerPort: 8080


---

kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
  labels:
    component: frontend-service
    project: expense
    environment: dev
spec:
  selector:
    component: frontend
    tier: web
    project: expense
    environment: dev
  ports:
  - port: 8080
    targetPort: 8080
      
